### PR TITLE
added a favicon to the webpage

### PR DESCRIPTION
**Pull request by ryanfortner**

### CODE REVIEW

**Comment by ryanfortner** [comment]
@LAX1DUDE why did you close the PR?

**Comment by orangemn6** [comment]
@ryanfortner it says in the readme not to edit anything in stable-download

**Comment by ryanfortner** [comment]
> @ryanfortner it says in the readme not to edit anything in stable-download

Alright. Please consider my contribution though, as I think the project could benefit from it.

**Comment by LAX1DUDE** [comment]
> Alright. Please consider my contribution though, as I think the project could benefit from it.

You screwed up the content type, you wrote it as image/png but then linked it to a random svg file, and it is on a totally different repository that I don't even own which means it is subject to change at any time. The file will eventually get renamed or deleted and everyone's sites will get messed up and they won't know why because they're stupid

If someone wants to use a registered microsoft trademark as their whole game's official favicon then they can make that decision themselves and download the file to a folder on their own domain instead of depending on some completely random unknown strangers not to move or delete that file on their end which you linked that is in a project they are still actively working on

I've been using github for a decent amount of time now and creating links that assume other people will never delete or rename a file on their own accounts like this, regardless if it is on a repository they are still commiting to or not, it never works out and is really annoying to try and fix if you can't even figure out what the original file even was years later

**Comment by Belladabest** [comment]
Mess arf and d.deev got blocked is there another one?

**Comment by 3kh0** [comment]
@Belladabest Please do not ask those types of questions here

**Comment by Belladabest** [comment]
@3kh0  I just wanna know dude

**Pull request closed without merging**
