### PR TITLE
Error Crash

### PR DESCRIPTION
**Pull request by AstroLive8333**
Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the issues feed of this fork's GitHub repository.

The URL to this fork's GitHub repository is: https://github.com/lax1dude/eaglercraft

Native Browser Exception
----------------------------------
  Line: 19414:393
  Type: Error
  Message: Java exception thrown
----------------------------------

Error: Java exception thrown
    at $rt_exception (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:155:390)
    at $rt_throw (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:155:218)
    at Pe (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:6360:139)
    at BkH (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:3815:302)
    at B$X (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:17430:289)
    at A1z.$rt_array.toString [as dM] (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:19192:42)
    at BdT (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:4547:402)
    at B3f (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:17434:150)
    at A1z.$rt_array.toString [as gG] (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:19192:112)
    at Beb (file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html:4556:145)

eaglercraft.version = "22w34d"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "eagtek"
eaglercraft.username = "AstroLive8333"

window.eaglercraftOpts = {"container":"game_frame","relays":[{"addr":"wss://relay.deev.is/","primary":false,"name":"lax1dude relay #1"},{"addr":"wss://relay.lax1dude.net/","primary":true,"name":"lax1dude relay #2"},{"addr":"wss://relay.shhnowisnottheti.me/","primary":false,"name":"ayunami relay #1"}],"serverListTitle":"Ayonull hosts a list of servers:","mainMenu":{"splashes":["Darviglet!","eaglerenophile!","You Eagler!","Yeeeeeee!","yeee","EEEEEEEEE!","You Darvig!","You Vigg!",":>","|>","You Yumpster!"]},"assetsURI":"data:application/octet-stream;base64,RUFHUEtHJCQGdmVyMi4wCmFzc2V0cy5lcGsAVgoKICMgIEVhZ2xlciBFUEsgdjIuMCAoYykgMjAyMiBDYWxkZXIgWW91bmcKICMgIHVwZGF0ZTogb24gMDgvMjkvMjAyMiBhdCAxMjoxNTo0NSBBTQoKAAABgufQBQgAAAVXRx+LCAAAAAAAAv/svHV4Fle3Nv4QLHjw4AQCRQYYn9lAg0uA8AK ... ","serverListLink":"https://eagler.nully.tech/servers","serverWorkerURI":"blob:null/38d850d9-ea1e-4ac0-87fe-31eb05f38af3","worldsFolder":"OFFLINE"}

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 12739.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1366
rootElement.clientHeight = 768
window.innerWidth = 1366
window.innerHeight = 768
window.outerWidth = 1366
window.outerHeight = 768
window.devicePixelRatio = 1
window.screen.availWidth = 1366
window.screen.availHeight = 768
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.currentContext = undefined

window.location.href = file:///home/chronos/u-16ac9219cd3544e23f3d31672620ad9a172dea5b/MyFiles/Downloads/Minecraft.html

----- Begin Minecraft Config -----
CgAAAwAIa2V5Lnpvb20AAAAuAwAMa2V5LnBpY2tJdGVt////ngEAD2NoYXRMaW5rc1Byb21wdAEDAAxrZXkuZnVuY3Rpb24AAAAhAwAIa2V5LmNoYXQAAAAUAQAOc2hvd1NraW5KYWNrZXQBAwAKa2V5LnNwcmludAAAABAFAAtzb3VuZFZvbHVtZT+AAAADAA5jaGF0VmlzaWJpbGl0eQAAAAEDABF2b2ljZUxpc3RlblJhZGl1cwAAAAoBABBzaG93U2tpblJpZ2h0TGVnAQMADWtleS5pbnZlbnRvcnkAAAASAQAPc2hvd1NraW5MZWZ0TGVnAQEAEWhpZGVTZXJ2ZXJBZGRyZXNzAAEADmFsbG93Rk5BV1NraW5zAAkAB3NlcnZlcnMBAAAAAAEADHJlbGF5VGltZW91dAQBAAt2aWV3Qm9iYmluZwEBABBhZHZhbmNlZFRvb2x0aXBzAAUAC2NoYXRPcGFjaXR5P4AAAAUAEXZvaWNlTGlzdGVuVm9sdW1lPwAAAAMACGtleS5iYWNrAAAAHwEADGhpZGVKb2luQ29kZQADAApmb3JjZVdpZHRoAAAAAAMADGNodW5rVXBkYXRlcwAAAAADAAhrZXkuZHJvcAAAAC8FAAttdXNpY1ZvbHVtZT+AAAAFAAtzZW5zaXRpdml0eT6wrRIBABBwYXVzZU9uTG9zdEZvY3VzAQMAC3ZvaWNlUFRUS2V5AAAAEwEAC3Nob3dTa2luSGF0AQUABWdhbW1hP4AAAAMACXBhcnRpY2xlcwAAAAIBAA5zaG93T3RoZXJDYXBlcwEBAAtjaGF0Q29sb3VycwEDAAhrZXkubGVmdAAAAB4DAAtrZXkuZm9yd2FyZAAAABEDAAprZXkuYXR0YWNr////nAMADHZpZXdEaXN0YW5jZQAAAAMBAApkaWZmaWN1bHR5AAEAA2ZvZwABAA9zaG93Q29vcmRpbmF0ZXMBAQAJY2hhdExpbmtzAQMACWtleS5zbmVhawAAACoDAAlrZXkucmlnaHQAAAAgBQADZm92AAAAAAUACWNoYXRXaWR0aD+AAAADAAhndWlTY2FsZQAAAAADAA5saW1pdEZyYW1lcmF0ZQAAAAAFAAljaGF0U2NhbGU/gAAAAQAIYWRkZXJhbGwAAQAUc2VlbkFja25vd2xlZGdlbWVudHMBAwAQYW1iaWVudE9jY2x1c2lvbgAAAAAIAAhsYW5ndWFnZQAFZW5fVVMBAAhhbmFnbHlwaAABABBoZWxkSXRlbVRvb2x0aXBzAQUAEWNoYXRIZWlnaHRGb2N1c2VkP4AAAAEAEHNob3dTa2luUmlnaHRBcm0BAQAKZnVsbFNjcmVlbgABAA9zaG93U2tpbkxlZnRBcm0BAwAIa2V5Lmp1bXAAAAA5AQAGY2xvdWRzAAUAE2NoYXRIZWlnaHRVbmZvY3VzZWQ+nqXcAQALdG91Y2hzY3JlZW4AAwAOa2V5LnBsYXllcmxpc3QAAAAPAQALaW52ZXJ0TW91c2UAAQAIc2hvd0NhcGUBAwANYW50aWFsaWFzTW9kZQAAAAEDAAtmb3JjZUhlaWdodAAAAAABAA1mYW5jeUdyYXBoaWNzAAMAB2tleS51c2X///+dCAAKbGFzdFNlcnZlcgAed3NzOi8vcGxheS52YW5pbGxhY3JhZnRzbXAub3JnBQAQdm9pY2VTcGVha1ZvbHVtZT+AAAAA
----- End Minecraft Config -----

window.minecraftServer = undefined

### CODE REVIEW

**Comment by ayunami2000** [comment]
Please discuss this on the Eaglercraft discord, not here.

**Comment by lax1dude** [comment]
Note to self: delete every branch on this repo except the main, regardless of how disorganized that may make things, so people have one fewer way to conveniently open unsolicited spam pull requests to circumvent my decision to disable issues

**Comment by lax1dude** [comment]
do you have any idea what pull request even means or did you just sit around mindlessly clicking stuff for 20 minutes until you got something to stick?

**Comment by AstroLive8333** [comment]
sorry

**Pull request closed without merging**
