### PR TITLE
yall bitches gimme back my roles 🥱

### PR DESCRIPTION
**Pull request by heartedart**
roles now or yo ass gets BEAT😹

### CODE REVIEW

**Comment by LAX1DUDE** [comment]
retard

**Comment by heartedart** [comment]
shut yo gay ass up @LAX1DUDE yo retarded white ass aint got no friends so just stfu and stop acting like yo so big and bad and nasty 😹

**Comment by heartedart** [comment]
ur broke ass aint gonna get u any bitches 💀 😂

**Comment by heartedart** [comment]
@LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE

**Comment by heartedart** [comment]
@LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE

**Comment by heartedart** [comment]
@LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE

**Comment by heartedart** [comment]
@LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE

**Comment by heartedart** [comment]
@LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE

**Comment by heartedart** [comment]
@LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE

**Comment by heartedart** [comment]
mf u better finna get me back my fye prof artist role or i finna raid yo server 😹 😹 😹

**Comment by Brenden2008** [comment]
can yall stop blowing up my email

**Comment by heartedart** [comment]
> can yall stop blowing up my email
> […](#)
> On 8/13/22, hearted ***@***.***> wrote: @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE -- Reply to this email directly or view it on GitHub: [#180 (comment)](https://github.com/LAX1DUDE/eaglercraft/pull/180#issuecomment-1214277025) You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

stfu lmaoooo u broke ass bitch names brendan 😂 😂

**Comment by heartedart** [comment]
you aint got no friends stfu

**Comment by Brenden2008** [comment]
i aint have no females but i do have a lot of money

**Comment by Brenden2008** [comment]
ight noted

**Comment by heartedart** [comment]
stfu u aint in this shit ☠️ 💀 😂

**Comment by Brenden2008** [comment]
well its in my email and its making me mad

**Comment by NoobPlayzlo** [comment]
> can yall stop blowing up my email
> […](#)
> On 8/13/22, hearted ***@***.***> wrote: @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE -- Reply to this email directly or view it on GitHub: [#180 (comment)](https://github.com/LAX1DUDE/eaglercraft/pull/180#issuecomment-1214277025) You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

dont listen to her, she just wants attention

**Comment by Brenden2008** [comment]
thx noobplayzlo its cool project but this pr is so dumb

**Comment by LAX1DUDE** [comment]
> > can yall stop blowing up my email
> > […](#)
> > On 8/13/22, hearted _**@**_._**> wrote: @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE @LAX1DUDE -- Reply to this email directly or view it on GitHub: [#180 (comment)](https://github.com/LAX1DUDE/eaglercraft/pull/180#issuecomment-1214277025) You are receiving this because you are subscribed to this thread. Message ID: _**@**_.**_>
> 
> dont listen to her, she just wants attention

What the fuck do you have to say about trying to get attention

**Comment by NoobPlayzlo** [comment]
nerd-nerd-emoji

**Comment by LAX1DUDE** [comment]
> nerd-nerd-emoji
> 
> 

you fucking retard that's not even the original gif, know your fucking memes before you try to be a player

**Pull request closed without merging**
