### PR TITLE
/give command thing

### PR DESCRIPTION
**Pull request by SmashHits**
when i use a command to give myself something it either says "[item] is an invalid number" or "player not found"

### CODE REVIEW

**Comment by ayunami2000** [comment]
http://mineteamleblog.blogspot.com/p/minecraft-id-list-151.html

e.g. `/give username 137` --> command block

do not post your issues here, go to the discord instead

**Comment by lax1dude** [comment]
lmao you figured out how to make a github account and then dig through this repo and figure out how to open a spam pull request without forking anything but then say you can't figure out how to use /give in your server

This is not my problem /give is server-side and I did not write bukkit or spigot so please QUITE LITERALLY go make a single google search and figure out how to solve this yourself

**Comment by SmashHits** [comment]
um, I'm sorry but when I googled it said to write the name as the item but when I tried it, it didn't work and I did not find anywhere that you have to put a number in to receive the item, I'm sorry for assuming this problem was on your side of the program, but maybe try a better tone when responding to the next user instead of telling them that they were oblivious within google searching and Minecraft.

**Comment by ayunami2000** [comment]
the tone is because you should NEVER EVER use the PR system to work around the intentionally disabled issues page EVER because that's just really really annoying to deal with after we TRIED to disable the issues page and yet here people are abusing the pull requests on GitHub to ask questions INSTEAD

**Pull request closed without merging**
