### PR TITLE
Newer Versions and Performance

### PR DESCRIPTION
**Pull request by SupremeRubisco**
Hi LAX1DUDE,

On the FAQ website run by Ayonull it says you are working on a 1.8.8 version. Why not 1.8.9? Also, are you going to add mods that will improve performance for the newer version, because currently 1.5.2 runs quite slow and newer versions will probably run even slower. 

Thanks and sorry for the trouble,
SupremeRubisco

### CODE REVIEW

**Comment by ReadingFear** [comment]
Eaglercraft is already pretty optimized for browsers, there probably isn't much room for improvement.

**Comment by LAX1DUDE** [comment]
> Eaglercraft is already pretty optimized for browsers, there probably isn't much room for improvement.

Yeah, the desktop debug runtime gets 1000fps on fancy graphics with my full mipmapping and anisotropic filtering and FXAA enabled on my newer computer, which is much well over double mojang's vanilla 1.5.2 performance on the same computer.

I've never used optifine before and experienced well over double the frame rate of vanilla with all the same fancy graphics enabled and with the same additional optifine equivalent of the advanced mipmapping and anisotropic filtering and antialiasing modes as what eagler comes with by default all also enabled at the max quality

**Comment by SupremeRubisco** [comment]
Well, for 1.8 there a couple of forge mods that optimize minecraft including optifine. I was just wondering if you were going to add those.

**Comment by LAX1DUDE** [comment]
>  Eaglercraft 1.5.2 runs fine but for 1.8 there a couple of forge mods that optimize minecraft including optifine. I was just wondering if you were going to add any of those.

I am aware, but considering I was more successful at my optimizations than optifine last time, I don't think porting portions of minecraft forge just so I can steal code from other peoples' mods instead of just optimizing it natively will be a priority when I create 1.8. I already have plans to optimize heavily in multiple browser specific ways that mods don't even exist for in the first place.

**Pull request closed without merging**
