### PR TITLE
hacks

### PR DESCRIPTION
**Pull request by Missyboi**
hi i was wondering if u knew how to put nodus on her
[nodus_1.5.2.zip](https://github.com/LAX1DUDE/eaglercraft/files/8856834/nodus_1.5.2.zip)

### CODE REVIEW

**Comment by ayunami2000** [comment]
no

**Comment by CrxckedDest0y3r** [comment]
suck my nuts

**Comment by sussygamedeveloper** [comment]
R E T A R D !

**Comment by LAX1DUDE** [comment]
tell us one time you did something smart on your own

**Comment by Missyboi** [comment]
i once made a pvp server on bedrock

**Comment by JVGA8837** [comment]
That’s like the easiest thing to do

**Comment by mdo992** [comment]
how do you understand this pr

**Comment by CrxckedDest0y3r** [comment]
I be stroking my dick, i got lotion on my dick

**Comment by mdo992** [comment]
> I be stroking my dick, i got lotion on my dick

https://user-images.githubusercontent.com/89719878/178661210-f34fc298-ad9d-4835-9b89-1aa8162cdf77.MOV

**Pull request closed without merging**
