### PR TITLE
Create Forge Mod

### PR DESCRIPTION
**Pull request by NoobPlayzlo**

### CODE REVIEW

**Comment by ColdDev** [comment]
kid can't you fuck off and find something better to do

**Comment by NoobPlayzlo** [comment]
didnt ask

**Comment by ColdDev** [comment]
> didnt ask

I asked, find something better to do with your time you fucking weirdo :skull:

**Comment by ColdDev** [comment]
imagine abusing GitHub's PR system

**Comment by NoobPlayzlo** [comment]
> > didnt ask
> 
> I asked, find something better to do with your time you fucking weirdo 💀

no, stfu

**Comment by NoobPlayzlo** [comment]
> imagine abusing GitHub's PR system

don't care

**Comment by ColdDev** [comment]
> > imagine abusing GitHub's PR system
> 
> don't care

I know you don't care because you don't get any bitches

**Comment by NoobPlayzlo** [comment]
> > > imagine abusing GitHub's PR system
> > 
> > 
> > don't care
> 
> I know you don't care because you don't get any bitches

did i ask?

**Comment by ColdDev** [comment]
> > > > imagine abusing GitHub's PR system
> > > 
> > > 
> > > don't care
> > 
> > 
> > I know you don't care because you don't get any bitches
> 
> did i ask?

yeah you did

**Comment by NoobPlayzlo** [comment]
> > > > > imagine abusing GitHub's PR system
> > > > 
> > > > 
> > > > don't care
> > > 
> > > 
> > > I know you don't care because you don't get any bitches
> > 
> > 
> > did i ask?
> 
> yeah you did

cry about it

**Comment by ColdDev** [comment]
> > > > > > imagine abusing GitHub's PR system
> > > > > 
> > > > > 
> > > > > don't care
> > > > 
> > > > 
> > > > I know you don't care because you don't get any bitches
> > > 
> > > 
> > > did i ask?
> > 
> > 
> > yeah you did
> 
> cry about it

why would I cry? I don't need to stoop this low and create a bunch of PRs for attention :D

**Comment by NoobPlayzlo** [comment]
> 

you have no friends, stfu

**Comment by ColdDev** [comment]
> > 
> 
> you have no friends, stfu

someone sounds mad, did I hit a soft spot?

**Comment by NoobPlayzlo** [comment]
> 

cope

**Comment by ColdDev** [comment]
> > 
> 
> cope

sounds like you're the only one coping here bud :sunglasses:

**Comment by NoobPlayzlo** [comment]
didn't ask

**Comment by ColdDev** [comment]
> didn't ask

your mom did

**Comment by NoobPlayzlo** [comment]
last time i checked your mom died giving birth to you

**Comment by NoobPlayzlo** [comment]
+ cope

**Comment by ColdDev** [comment]
> last time i checked your mom died giving birth to you

looks like I hit a soft spot again

**Comment by Fangoboyo** [comment]
"last time i checked your mom died giving birth to you" - 🤡

**Comment by ColdDev** [comment]
you sure you're not projecting? :D

**Comment by NoobPlayzlo** [comment]
> "last time i checked your mom died giving birth to you" - 🤡

ratio

**Comment by ColdDev** [comment]
got something to share with the class?

**Comment by ColdDev** [comment]
> > "last time i checked your mom died giving birth to you" - clown_face
> 
> ratio

counter ratio

**Comment by NoobPlayzlo** [comment]
> got something to share with the class?

juts that you're a retard

**Comment by Fangoboyo** [comment]
> > "last time i checked your mom died giving birth to you" - 🤡
> 
> ratio
"ratio" - 🤡

**Comment by ColdDev** [comment]
> 

damn I guess I did hit a soft spot

**Comment by NoobPlayzlo** [comment]
> > 
> 
> damn I guess I did hit a soft spot

you have no friends

**Comment by ColdDev** [comment]
> > > 
> > 
> > 
> > damn I guess I did hit a soft spot
> 
> you have no friends

someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines

**Comment by Fangoboyo** [comment]
> > got something to share with the class?
> 
> juts that you're a retard

just*

**Comment by NoobPlayzlo** [comment]
> > > > 
> > > 
> > > 
> > > damn I guess I did hit a soft spot
> > 
> > 
> > you have no friends
> 
> someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines

how much chromosones do you have?

**Comment by NoobPlayzlo** [comment]
> > > got something to share with the class?
> > 
> > 
> > juts that you're a retard
> 
> just*

how much chromosones do you have?

**Comment by ColdDev** [comment]
> > > > > 
> > > > 
> > > > 
> > > > damn I guess I did hit a soft spot
> > > 
> > > 
> > > you have no friends
> > 
> > 
> > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> 
> how much chromosones do you have?

chromosomes*

**Comment by Fangoboyo** [comment]
> > > > got something to share with the class?
> > > 
> > > 
> > > juts that you're a retard
> > 
> > 
> > just*
> 
> how much chromosones do you have?

how many*

**Comment by NoobPlayzlo** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > damn I guess I did hit a soft spot
> > > > 
> > > > 
> > > > you have no friends
> > > 
> > > 
> > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> > 
> > 
> > how much chromosones do you have?
> 
> chromosomes*

🤡

**Comment by ColdDev** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > damn I guess I did hit a soft spot
> > > > > 
> > > > > 
> > > > > you have no friends
> > > > 
> > > > 
> > > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> > > 
> > > 
> > > how much chromosones do you have?
> > 
> > 
> > chromosomes*
> 
> clown_face

"clown_face" - :clown_face:

**Comment by NoobPlayzlo** [comment]
> > > > > got something to share with the class?
> > > > 
> > > > 
> > > > juts that you're a retard
> > > 
> > > 
> > > just*
> > 
> > 
> > how much chromosones do you have?
> 
> how many*

🤓

**Comment by NoobPlayzlo** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > damn I guess I did hit a soft spot
> > > > > > 
> > > > > > 
> > > > > > you have no friends
> > > > > 
> > > > > 
> > > > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> > > > 
> > > > 
> > > > how much chromosones do you have?
> > > 
> > > 
> > > chromosomes*
> > 
> > 
> > clown_face
> 
> "clown_face" - 🤡

ratio

**Comment by ColdDev** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > damn I guess I did hit a soft spot
> > > > > > > 
> > > > > > > 
> > > > > > > you have no friends
> > > > > > 
> > > > > > 
> > > > > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> > > > > 
> > > > > 
> > > > > how much chromosones do you have?
> > > > 
> > > > 
> > > > chromosomes*
> > > 
> > > 
> > > clown_face
> > 
> > 
> > "clown_face" - clown_face
> 
> ratio

counter ratio

**Comment by NoobPlayzlo** [comment]
> > > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > damn I guess I did hit a soft spot
> > > > > > > > 
> > > > > > > > 
> > > > > > > > you have no friends
> > > > > > > 
> > > > > > > 
> > > > > > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> > > > > > 
> > > > > > 
> > > > > > how much chromosones do you have?
> > > > > 
> > > > > 
> > > > > chromosomes*
> > > > 
> > > > 
> > > > clown_face
> > > 
> > > 
> > > "clown_face" - clown_face
> > 
> > 
> > ratio
> 
> counter ratio

don't care, didn't ask

**Comment by ColdDev** [comment]
> > > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > damn I guess I did hit a soft spot
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > you have no friends
> > > > > > > > 
> > > > > > > > 
> > > > > > > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> > > > > > > 
> > > > > > > 
> > > > > > > how much chromosones do you have?
> > > > > > 
> > > > > > 
> > > > > > chromosomes*
> > > > > 
> > > > > 
> > > > > clown_face
> > > > 
> > > > 
> > > > "clown_face" - clown_face
> > > 
> > > 
> > > ratio
> > 
> > 
> > counter ratio
> 
> don't care, didn't ask

your mom did

**Comment by LAX1DUDE** [comment]
> > > > > > > > > > > 
> 
> > > > > > > > > > 
> 
> > > > > > > > > > 
> 
> > > > > > > > > > damn I guess I did hit a soft spot
> 
> > > > > > > > > 
> 
> > > > > > > > > 
> 
> > > > > > > > > you have no friends
> 
> > > > > > > > 
> 
> > > > > > > > 
> 
> > > > > > > > someone sounds mad, you projecting again buddy? I can hook you up with multiple suicide prevention lines
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > how much chromosones do you have?
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > chromosomes*
> 
> > > > > 
> 
> > > > > 
> 
> > > > > clown_face
> 
> > > > 
> 
> > > > 
> 
> > > > "clown_face" - clown_face
> 
> > > 
> 
> > > 
> 
> > > ratio
> 
> > 
> 
> > counter ratio
> 
> 
> 
> don't care, didn't ask

Squawk Squawk Squawk!

**Comment by NoobPlayzlo** [comment]
nerd-nerd-emoji

**Pull request closed without merging**
