### PR TITLE
Assorted prose fixes

### PR DESCRIPTION
**Pull request by Makonede**

### CODE REVIEW

**Comment by UnknownKeeper82828** [comment]
🗿

**Comment by lax1dude** [comment]
I feel dumb saying this, but practically all of these 'mistakes' are my attempt at trying to make the documentation more relatable to the average person reading it, I find it less intimidating to people who are actually reading this to type it in the same typing style they prefer to type in when they're actually messaging REAL people about this project vs just a wall of pre-formatted technical instructions 

It's a pain in the ass to try and make people actually read this full documentation without 'giving up' because they find it too intimidating, the least I can do is minimize the amount of unnecessary grammar these people have to process visually when they read this that they don't have to process when they ask and get answers to their questions on stuff like discord.

This is not a final verdict at all to this PR, I understand some people are actually mature enough to be able to read this more easily if the typing style is more professional, but for easily the largest percentage of people reading this it's only a distraction to have this degree of attention to detail in their reading material

Leaving this comment is definitely an embarrassment to me professionally, but I'd take that over more people being overly intimidated by the README

**Comment by lax1dude** [comment]
And I'm not closing this or anything either, for all I know this issue is a lapse in my own judgment, but I do want to get the way I felt in the moment out there if we want to be this anal about typing styles

**Comment by cleitinabarata** [comment]
Mn poderia trazer uma versão tipo 1.18 seria uma boa

**Comment by Makonede** [comment]
Not possible @cleitinabarata, 1.5.2 is the last playable Minecraft version without requiring a download. Also, why'd you comment on this PR? Not even relevant.

**Comment by lax1dude** [comment]
> Mn poderia trazer uma versão tipo 1.18 seria uma boa

This isn't a forum please ask somewhere else

**Comment by notaux** [comment]
@lax1dude um im kinda new to eagler craft and so is my friend. Um my friend is a script kiddie and doesnt know shit and he begged me to ask you he wants to know if its possible to import the git onto replit and remake eagler craft.

**Comment by notaux** [comment]
@lax1dude can i get the encryption key i wanna try to recode eagler craft?

**Comment by strubium** [comment]
> I feel dumb saying this, but practically all of these 'mistakes' are my attempt at trying to make the documentation more relatable to the average person reading it, I find it less intimidating to people who are actually reading this to type it in the same typing style they prefer to type in when they're actually messaging REAL people about this project vs just a wall of pre-formatted technical instructions
> 
> It's a pain in the ass to try and make people actually read this full documentation without 'giving up' because they find it too intimidating, the least I can do is minimize the amount of unnecessary grammar these people have to process visually when they read this that they don't have to process when they ask and get answers to their questions on stuff like discord.
> 
> This is not a final verdict at all to this PR, I understand some people are actually mature enough to be able to read this more easily if the typing style is more professional, but for easily the largest percentage of people reading this it's only a distraction to have this degree of attention to detail in their reading material
> 
> Leaving this comment is definitely an embarrassment to me professionally, but I'd take that over more people being overly intimidated by the README

These ARE mistakes tho, I mean yeah changing "join discord" to Join the Discord" doesn't help a lot, But ANY improvements should be added. 

It doesn't even change the general formatting to be more "professional" It just added some periods and capitals.

**Comment by lax1dude** [comment]
> These ARE mistakes tho, I mean yeah changing "join discord" to Join the Discord" doesn't help a lot, But ANY improvements should be added.

nice job with those quotation marks I can really tell how passionate you are about correcting peoples grammar as a passtime

**Comment by lax1dude** [comment]
you really caught me red handed in that other PR you dug up too, kudos to you for teaching me so much about how to speak english

**Comment by NoobPlayzlo** [comment]
> 

💀 this isn't even your project, why are you looking at random repos and coming in here and being a condescending and authoritative shit? you need find a hobby

**Comment by lax1dude** [comment]
I wouldn't even have minded his input here if it wasn't for his second comment on the other PR

**Comment by notaux** [comment]
ay @lax1dude sorry for my friend hounding you he was at my house while i went outside with my other friends and hes a script kiddie sorry about that hope you can forgive him or me :| thanks

**Comment by strubium** [comment]
> > These ARE mistakes tho, I mean yeah changing "join discord" to Join the Discord" doesn't help a lot, But ANY improvements should be added.
> 
> nice job with those quotation marks I can really tell how passionate you are about correcting peoples grammar as a passtime

yes

**Comment by CROUCH79** [comment]
hi i like eaglercraft i airdroped it to my friends and now they airdroped it to random people and then basicly the whole school has it now and the funny thing is they keep on getting demarits and the cant block it

**Review by 3kh0 — APPROVED** [review]
I don't know if my input is need but these grammar changes are correct.

**Comment by Hellscap3d** [comment]
> I don't know if my input is needed but these grammar changes are correct.

lax doesn't want them

he doesn't need them

the corrections just make it harder for the average person to understand what he is saying

**Comment by lax1dude** [comment]
> 
> 
> 
> lax doesn't want them
> 
> 
> 
> he doesn't need them
> 
> 
> 
> the corrections just make it harder for the average person to understand what he is saying

I never said that I'm just too busy to deal with any of this right now

**Comment by WindowsRefundDay** [comment]
people are probably going to use this pr as means of telling their stupid questions

**Comment by CROUCH79** [comment]
i tried running one of my eaglercraft backup world because they all disapeared when i tried updating google chrome but then this error message happened every single time i tried Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the #debugging channel in the official Eaglercraft discord server

Join the discord server at: https://discord.gg/Ekzcgs3DKZ

The URL to this fork's GitHub repository is: https://github.com/lax1dude/eaglercraft

Native Browser Exception
----------------------------------
  Line: 19566:393
  Type: Error
  Message: Java exception thrown
----------------------------------

Error: Java exception thrown
    at $rt_exception (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:155:390)
    at $rt_throw (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:155:218)
    at Pq (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:6377:142)
    at Bwp (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:17652:112)
    at $rt_array.toString [as fc] (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:19286:491)
    at BGT (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:3775:434)
    at BrI (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:3739:190)
    at BVe (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:3736:183)
    at BEE (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:218:155)
    at B$0 (file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html:214:11)


eaglercraft.version = "22w38a"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "eagtek"
eaglercraft.username = "Justin"

window.eaglercraftOpts = {"container":"game_frame","relays":[{"addr":"wss://relay.deev.is/","primary":false,"name":"lax1dude relay #1"},{"addr":"wss://relay.lax1dude.net/","primary":false,"name":"lax1dude relay #2"},{"addr":"wss://relay.shhnowisnottheti.me/","primary":true,"name":"ayunami relay #1"}],"serverListTitle":"Ayonull hosts a list of servers:","mainMenu":{"splashes":["Darviglet!","eaglerenophile!","You Eagler!","Yeeeeeee!","yeee","EEEEEEEEE!","You Darvig!","You Vigg!",":>","|>","You Yumpster!"]},"assetsURI":"data:application/octet-stream;base64,RUFHUEtHJCQGdmVyMi4wCmFzc2V0cy5lcGsAVgoKICMgIEVhZ2xlciBFUEsgdjIuMCAoYykgMjAyMiBDYWxkZXIgWW91bmcKICMgIHVwZGF0ZTogb24gMDkvMDEvMjAyMiBhdCAxMTowNDoxNiBQTQoKAAABgvzMy0IAAAVRRx+LCAAAAAAAAv/svHV4Fle3Nv4QLHjw4AQCRQYYn9lAg0uA8AK ... ","serverListLink":"https://eagler.nully.tech/servers","serverWorkerURI":"blob:null/ed01da9c-2353-4c36-b90a-44c609e971af","worldsFolder":"OFFLINE"}

window.navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 8
window.navigator.deviceMemory = 8
window.navigator.platform = MacIntel
window.navigator.product = Gecko

rootElement.clientWidth = 1200
rootElement.clientHeight = 658
window.innerWidth = 1200
window.innerHeight = 658
window.outerWidth = 1200
window.outerHeight = 769
window.devicePixelRatio = 2
window.screen.availWidth = 1440
window.screen.availHeight = 810
window.screen.colorDepth = 30
window.screen.pixelDepth = 30

window.currentContext = undefined

window.location.href = file:///Users/crouch79/Desktop/minecraft/Offline_Download_Version.html

----- Begin Minecraft Config -----
CgAAAQAUc2VlbkFja25vd2xlZGdlbWVudHMBAA==
----- End Minecraft Config -----

window.minecraftServer = undefined

**Comment by notaux** [comment]
bro how did my repo become so famous ITS LEGIT OPEN WHEN IT WAS CANCELED TF

**Comment by Makonede** [comment]
@CROUCH79 You've been told multiple times, this is not a forum thread, don't chat or ask for help here.

**Pull request closed without merging**
