### PR TITLE
pvpskin

### PR DESCRIPTION
**Pull request by deathgod2309**
image

### CODE REVIEW

**Comment by lax1dude** [comment]
bruh that's not how you add a skin 🤦‍♂️

sorry but I'm just not looking for these kinds of changes right now, forks and pull requests are meant for code contributing code

**Comment by HenryMKim** [comment]
> image

retard

**Comment by HenryMKim** [comment]
> bruh that's not how you add a skin 🤦‍♂️
> 
> sorry but I'm just not looking for these kinds of changes right now, forks and pull requests are meant for contributing code

shut yo gay ass up

**Comment by WritingFear** [comment]
> > bruh that's not how you add a skin 🤦‍♂️
> > sorry but I'm just not looking for these kinds of changes right now, forks and pull requests are meant for contributing code
> 
> shut yo gay ass up

💀

**Pull request closed without merging**
