### PR TITLE
Redesign of README.md

### PR DESCRIPTION
**Pull request by DiffuseHyperion**
for a long time, I thought that the current readme was really cluttered, confusing and unfriendly towards new players, since information was scattered around the file, and specific details like reverse proxy and client hosting was left out.
the main goal of this is provide an easy to follow readme and concise tutorials, with more advanced configurations in different sections. 

the table of contents near the beginning of the file should help readers to find specific information quickly, and i've left most of the original text unedited, just rearranged around

there are probably some of grammar mistakes due to me leaving text mostly unedited, hopefully contributors can iron those out

anyways hope this gets accepted :))))

### CODE REVIEW

**Review by 3kh0 — APPROVED** [review]
This looks so much better! Thanks!

**Comment by ayunami2000** [comment]
Ok this DOES look quite nice, I'd accept personally, but checking with lax.

**Comment by strubium** [comment]
Yo! This looks great!

**Comment by lax1dude** [comment]
Nice, I can't find any mistakes in this, the guide is 100% correct. Good job, merged.

**Pull request merged**
