### PR TITLE
Encryption

### PR DESCRIPTION
**Pull request by notaux**
I wanted to remake eaglercraft but the js is encrypted and i cant decrypt it can you give me the encryption pass or send me a js file of eaglercraft but in decrypted form please and thank you. @lax1dude

### CODE REVIEW

**Comment by lax1dude** [comment]
1. It's not encrypted it's just minified

2. The game is in java not javascript, edit the code in `src/main/java` and `src/teavm/java` and then run `./gradlew.bat` to re-generate the javascript with your changes

If you don't understand what I mean it's not my problem, I don't have time to teach you how to program via leaving comments on spam pull requests, if you make another pull request for a reason other then contributing commits from your fork then you will be blocked. Sorry.

**Comment by notaux** [comment]
What? what did i do lol i was just trying to remake it sorry.

**Comment by lax1dude** [comment]
`./gradlew.bat teavmc`

**Comment by notaux** [comment]
i went into *src/main/java am i supposed to click net then minecraft.java?

**Comment by notaux** [comment]
Im new to this im very sorry.

**Comment by notaux** [comment]
i wanted to change the name and give credit in the txt in top right but idk how lmao

**Comment by notaux** [comment]
also not by <title> in html but on the actual website where it says eaglercraft javasript runtime. @lax1dude

**Comment by lax1dude** [comment]
I said this is not my problem, figure this out yourself instead of abusing github's PR system to spam my inbox

**Comment by notaux** [comment]
just tell me pls

**Comment by lax1dude** [comment]
> just tell me pls

I fucking did, my very first comment on this PR is me explaining to you what to do, stop being a jackass and appreciate the effort I did make to help you despite your now ongoing choice to abuse github's PR system to harass me

**Comment by notaux** [comment]
when i go into it i dont know where im going you didnt specify if i go into minecraft.java or eaglercraft/net plus when i go into both i dont know where i change the name at so thats all  im asking jeez

**Comment by Hellscap3d** [comment]
people are fucking retarded

**Comment by notaux** [comment]
ong (including me :) )

**Comment by strubium** [comment]
> > just tell me pls
> 
> I fucking did, my very first comment on this PR is me explaining to you what to do, stop being a jackass and appreciate the effort I did make to help you despite your now ongoing choice to abuse github's PR system to harass me

"appreciate the effort I did" @lax1dude

**Comment by NoobPlayzlo** [comment]
> > > just tell me pls
> > 
> > 
> > I fucking did, my very first comment on this PR is me explaining to you what to do, stop being a jackass and appreciate the effort I did make to help you despite your now ongoing choice to abuse github's PR system to harass me
> 
> "appreciate the effort I did" @lax1dude

it's "I did make" you fucking idiot :skull:

**Comment by NoobPlayzlo** [comment]
imagine going on a random repo and searching for tiny (perceived) mistakes to make fun of and try to be cool

**Comment by strubium** [comment]
> imagine going on a random repo and searching for tiny (perceived) mistakes to make fun of and try to be cool

I find it funny, but yeah, the mistake is definitely tiny

**Comment by lax1dude** [comment]
> > > just tell me pls
> 
> > 
> 
> > I fucking did, my very first comment on this PR is me explaining to you what to do, stop being a jackass and appreciate the effort I did make to help you despite your now ongoing choice to abuse github's PR system to harass me
> 
> 
> 
> "appreciate the effort I did" @lax1dude  

what are you even trying to say, me saying "appreciate the effort I did make" is not incorrect grammar in the context of this spammer claiming that I *didn't* try to make an effort to help them. Fuck off

**Comment by NoobPlayzlo** [comment]
> > imagine going on a random repo and searching for tiny (perceived) mistakes to make fun of and try to be cool
> 
> I find it funny, but yeah, the mistake is definitely tiny

curious, what's going on inside your head when you decide to be a fucking smartass whenever anyone says something to you? do you want to be cool? do you think it makes you look smart? do you need professional help?

**Comment by notaux** [comment]
bro wtf is this first im sorry @everyone for my friend being a total retarded crusader okay but you dont need to act cool to get @lax1dude attention okay? like this isnt even your guy's repo so stfu

**Comment by NoobPlayzlo** [comment]
> bro wtf is this first im sorry @everyone for my friend being a total retarded crusader okay but you dont need to act cool to get @lax1dude attention okay? like this isnt even your guy's repo so stfu

i was talking to someone else, look at the reply chain :skull:

**Pull request closed without merging**
