### PR TITLE
add splash

### PR DESCRIPTION
**Pull request by Abnumality**

### CODE REVIEW

**Comment by Abnumality** [comment]
Among us

**Comment by ReadingFear** [comment]
You left a windows shortcut in src/main/java/net/minecraft/src in the last commit

**Comment by Abnumality** [comment]
> You left a windows shortcut in src/main/java/net/minecraft/src in the last commit

it was in the very first commit that was reverted

**Comment by ReadingFear** [comment]
> > You left a windows shortcut in src/main/java/net/minecraft/src in the last commit
> 
> it was in the very first commit that was reverted

Oh shit, I'm stupid

**Comment by ReadingFear** [comment]
sorry

**Comment by ReadingFear** [comment]
> > You left a windows shortcut in src/main/java/net/minecraft/src in the last commit
> 
> it was in the very first commit that was reverted

Oh, sorry

**Pull request closed without merging**
