### PR TITLE
Create Epic SMP

### PR DESCRIPTION
**Pull request by NoobPlayzlo**

### CODE REVIEW

**Comment by ayunami2000** [comment]
sick idea, maybe you could do it? see what's possible! (but this isnt the place to ask for it to be made for you, so i am unfortunately closing this issue...)

**Comment by LAX1DUDE** [comment]
dude shut up I've already had to close this once before why did you go make a new one again 

pull requests are in no way a feature request form, and if they were I would still ignore this because there's no code in this repository related to the public server list and it's not my responsibility to just up and host you a proxy service to some random server I've never heard of just because you shitposted the three words "Create Epic SMP" on my repository with no description 

I don't even run any servers in the first place, that hasn't been a thing since january, delete your github account and find something better to do with your time then abuse pull requests to contact me because issues are no longer available

**Comment by NoobPlayzlo** [comment]
wtf is wrong with you

**Comment by NoobPlayzlo** [comment]
just give me an eaglecraft

**Comment by ReadingFear** [comment]
Some people these days

**Comment by LAX1DUDE** [comment]
> just give me an eaglecraft

nice grammar

**Comment by THEBEST1278** [comment]
Lmao this kid 🤦‍♀️🤦‍♀️

**Pull request closed without merging**
