### PR TITLE
Updated Eaglercraft logo

### PR DESCRIPTION
**Pull request by xIcee**
I replaced the Minecraft logo in the title screen with a custom Eaglercraft one!
For it to work, though, the minceraft would have to be disabled, because as of now it happens all the time.
I don't know what it takes to make that happen, because I can't code for shit, but it needs to be disabled.
That's pretty much it.

### CODE REVIEW

**Comment by LAX1DUDE** [comment]
This is cool, we can look into this tomorrow, but I'm not sure if I want to completely replace the vanilla logo by default because my goal with eagler was never to rebrand the entire game. My goal was always to provide the most complete browser minecraft possible, the title screen is a very iconic piece of the game and I personally prefer the familiarity of the vanilla minecraft logo (despite the E and C swapped, but from the vanilla code) and I feel like it would change the first impression of the game from being "perfect 1:1 browser minecraft port" to "random browser game based on minecraft" for most people loading it for the first time when they don't see the logo we all grew up with for years and years back in the golden days of java edition

This can probably work out as some kind of 'eagler' flag you can change in `window.minecraftOpts` or something to show this logo instead or use to disable the 'minceraft' easter egg on the vanilla logo's code so resource pack developers can also easily make replacement title screens like this one without the minceraft texture mapping confusion. Maybe we can add a config file you can put in an EPK file you can use to set it not to do the minceraft easter egg in the texture code so a title screen change in an EPK like this would work without any additional configuration or work to reverse engineer how the minceraft easter egg is even rendered (because I still don't know how to reproduce it in an image editor, and definitely not in reverse)

**Comment by xIcee** [comment]
That seems reasonable enough. My first impression of eaglercraft was quite surprising at first, and I guess the Minecraft logo did separate it from clones. I never really thought about it that way, and it makes sense. Making an option to toggle this logo and the official minecraft one would be on the player for stylistic choice. Perhaps finding a way to implement client resource packs could help, too. Maybe an import/choose file dialog?

**Comment by Abnumality** [comment]
how do i add the eagle crafm replit

**Comment by ayunami2000** [comment]
> how do i add the eagle crafm replit

Thanks. This fix worked for me!

**Comment by Abnumality** [comment]
> This is cool, we can look into this tomorrow, but I'm not sure if I want to completely replace the vanilla logo by default because my goal with eagler was never to rebrand the entire game. My goal was always to provide the most complete browser minecraft possible, the title screen is a very iconic piece of the game and I personally prefer the familiarity of the vanilla minecraft logo (despite the E and C swapped, but from the vanilla code) and I feel like it would change the first impression of the game from being "perfect 1:1 browser minecraft port" to "random browser game based on minecraft" for most people loading it for the first time when they don't see the logo we all grew up with for years and years back in the golden days of java edition
> 
> This can probably work out as some kind of 'eagler' flag you can change in `window.minecraftOpts` or something to show this logo instead or use to disable the 'minceraft' easter egg on the vanilla logo's code so resource pack developers can also easily make replacement title screens like this one without the minceraft texture mapping confusion. Maybe we can add a config file you can put in an EPK file you can use to set it not to do the minceraft easter egg in the texture code so a title screen change in an EPK like this would work without any additional configuration or work to reverse engineer how the minceraft easter egg is even rendered (because I still don't know how to reproduce it in an image editor, and definitely not in reverse)

I love you

**Comment by LAX1DUDE** [comment]
> > This is cool, we can look into this tomorrow, but I'm not sure if I want to completely replace the vanilla logo by default because my goal with eagler was never to rebrand the entire game. My goal was always to provide the most complete browser minecraft possible, the title screen is a very iconic piece of the game and I personally prefer the familiarity of the vanilla minecraft logo (despite the E and C swapped, but from the vanilla code) and I feel like it would change the first impression of the game from being "perfect 1:1 browser minecraft port" to "random browser game based on minecraft" for most people loading it for the first time when they don't see the logo we all grew up with for years and years back in the golden days of java edition
> > This can probably work out as some kind of 'eagler' flag you can change in `window.minecraftOpts` or something to show this logo instead or use to disable the 'minceraft' easter egg on the vanilla logo's code so resource pack developers can also easily make replacement title screens like this one without the minceraft texture mapping confusion. Maybe we can add a config file you can put in an EPK file you can use to set it not to do the minceraft easter egg in the texture code so a title screen change in an EPK like this would work without any additional configuration or work to reverse engineer how the minceraft easter egg is even rendered (because I still don't know how to reproduce it in an image editor, and definitely not in reverse)
> 
> I love you

I love you too sunshine

**Comment by ayunami2000** [comment]
ayunami2000
can this be a new skin Plzzzz i love this skin so much !!

i love you  @LAX1DUDE please replity

**Comment by xIcee** [comment]
image
This is what the texture looks like in regular Minecraft 1.5.2 what do you think?

**Comment by xIcee** [comment]
> ...or work to reverse engineer how the minceraft easter egg is even rendered (because I still don't know how to reproduce it in an image editor, and definitely not in reverse)

I don't understand the code part of it, but by dissecting the image file I found out how it was likely done. Here's a color-coded example

mclogo

**Comment by literally1984** [comment]
> how do i add the eagle crafm replit

LGTM!

**Comment by zahin45** [comment]
> wait why no texture packs in Eaglercraft 1.5.2?
u have to make them ur self

**Comment by princephilli** [comment]
can the person that created this minecraft server put in a line of code giving prince_phillip admin

**Comment by princephilli** [comment]
my co worker or_Eo17 did this

**Comment by princephilli** [comment]
please

**Comment by princephilli** [comment]
she has too much power

**Comment by princephilli** [comment]
she thinks she owns the server

**Comment by ReadingFaer** [comment]
💀

**Comment by princephilli** [comment]
please

**Comment by lax1dude** [comment]
> can the person that created this minecraft server put in a line of code giving prince_phillip admin

what minecraft server?

even if I did know who your ex wife is who you're having this battle over custody of your minecraft server with then idk what I'm supposed to do to the client or proxy that'll randomly give you admin permissions on a server running a permission system I didn't create

**Comment by princephilli** [comment]
your not the creator of https://nicholasneums-public-eaglecrafter.nicholasneum.repl.co/

**Comment by ReadingFaer** [comment]
> your not the creator of https://nicholasneums-public-eaglecrafter.nicholasneum.repl.co/

Wow, you're really stupid

**Comment by princephilli** [comment]
sorry for the inconveinence

**Comment by XxT0mmyxX** [comment]
These are some uh, i n t e r e s t i n g comments ;-;

**Comment by XxT0mmyxX** [comment]
> These are some uh, i n t e r e s t i n g comments ;-;

Anyways how do you make a "wss:// "??

**Comment by lax1dude** [comment]
> > your not the creator of https://nicholasneums-public-eaglecrafter.nicholasneum.repl.co/
> 
> 
> 
> Wow, you're really stupid

yeah, idk what you're trying to say @princephilli, you're asking me to backdoor everyone's client so you can get admin permissions on your ex's eaglercraft server, and then I tell you that's an impossible an absurd request, and now you're like "your not the creator of" and then a replit link that there's no way in hell I'm gonna click.

what are you trying to say? that I do secretly own the server? or did you absent mindedly read my response and think I claim that I am and that I'm wrong? either way why do you think that's gonna get you what you want here

by the way this is a pull request, not a relationship advice mailing list, please look up how github is supposed to be used and don't use it as spam

**Comment by princephilli** [comment]
ok

**Comment by Dillan-Bowman** [comment]
i installed the "craftbook" plugin into my server, and made some server artifacts in the following file:
`java/bukkit_command/plugins/CraftBook/command-items.yml`
so i was wondering if there was a way to install a texture pack of some sort into a server files specifically or to add new items via a different plugin to base the artifacts off of (ex: i got an "warp wand" artifact which is just a stick infused with /jump , and would like to create a new texture and item database number that would better fit the wand)

**Comment by lax1dude** [comment]
> i installed the "craftbook" plugin into my server, and made some server artifacts in the following file: `java/bukkit_command/plugins/CraftBook/command-items.yml` so i was wondering if there was a way to install a texture pack of some sort into a server files specifically or to add new items via a different plugin to base the artifacts off of (ex: i got an "warp wand" artifact which is just a stick infused with /jump , and would like to create a new texture and item database number that would better fit the wand)

off topic, please take this somewhere else, I'm tired of people abusing comments in PRs or opening new PRs to ask questions that don't have anything to do with the patch being submitted

**Comment by Dillan-Bowman** [comment]
> > i installed the "craftbook" plugin into my server, and made some server artifacts in the following file: `java/bukkit_command/plugins/CraftBook/command-items.yml` so i was wondering if there was a way to install a texture pack of some sort into a server files specifically or to add new items via a different plugin to base the artifacts off of (ex: i got an "warp wand" artifact which is just a stick infused with /jump , and would like to create a new texture and item database number that would better fit the wand)
> 
> off topic, please take this somewhere else, I'm tired of people abusing comments in PRs or opening new PRs to ask questions that don't have anything to do with the patch being submitted

damn, sorry

**Comment by pazza08223** [comment]
This is really cool, what if the creator of the server can set a custom name for the logo

**Comment by xIcee** [comment]
this has just become a sort of issue or request forum, huh? If that's the case, are you still working on 1.8.8/1.8.9, and if so, how's progress in that coming along?

**Comment by ayunami2000** [comment]
> this has just become a sort of issue or request forum, huh? If that's the case, are you still working on 1.8.8/1.8.9, and if so, how's progress in that coming along?

NO IT ISNT SHUT THE FUCK UP

**Comment by ReadingFaer** [comment]
> > this has just become a sort of issue or request forum, huh? If that's the case, are you still working on 1.8.8/1.8.9, and if so, how's progress in that coming along?
> 
> 
> 
> NO IT ISNT SHUT THE FUCK UP

That's not what he asked 💀

**Comment by ayunami2000** [comment]
> > > this has just become a sort of issue or request forum, huh? If that's the case, are you still working on 1.8.8/1.8.9, and if so, how's progress in that coming along?
> > 
> > 
> > NO IT ISNT SHUT THE FUCK UP
> 
> That's not what he asked 💀

It's not an issue or request form so shut up and respect lax's message please. All of you. You're driving this issue to the grave with every off topic message.

**Comment by lax1dude** [comment]
> this has just become a sort of issue or request forum, huh? If that's the case, are you still working on 1.8.8/1.8.9, and if so, how's progress in that coming along?

did you literally not read how I wrote "off topic, please take this somewhere else, I'm tired of people abusing comments in PRs or opening new PRs to ask questions that don't have anything to do with the patch being submitted" less then 24 hours ago?

we're 'merging' (closing) this in a few days when we merge singleplayer/lan because I did actually add this to the game over on that branch but I had to do a ton of work on it because it was blurry from the antialiasing and the colors were off and, well, it's the title screen so I want to give a good first impression. I removed the minceraft easter egg and instead modified the actual minecraft logo png to show minceraft normally like your diagram. The `minecraftOpts` field has been replaced with an `eaglercraftOpts` field that's json based and if you add `eaglerLogo: true` to the `mainMenu` part it'll show this logo.

**Comment by ZGStuff** [comment]
pls do, im tired of this

**Comment by NoobPlayzlo** [comment]
> > > > this has just become a sort of issue or request forum, huh? If that's the case, are you still working on 1.8.8/1.8.9, and if so, how's progress in that coming along?
> > > 
> > > 
> > > NO IT ISNT SHUT THE FUCK UP
> > 
> > 
> > That's not what he asked 💀
> 
> It's not an issue or request form so shut up and respect lax's message please. All of you. You're driving this issue to the grave with every off topic message.

stop your annoying lax1dude, @lax1dude dont listen to him

**Comment by NoobPlayzlo** [comment]
btw @ayunami2000 how do i make a repl sever

**Comment by NoobPlayzlo** [comment]
i think u can help bc ur lax1dudes friend and im friends with him too

**Comment by NoobPlayzlo** [comment]
im trying to get those tokens but idk how to

**Comment by xIcee** [comment]
ok :) closing

**Comment by xIcee** [comment]
wait i didnt fully read sorry

**Comment by xIcee** [comment]
I didn't fully read and closed this prematurely. Sorry about asking, and I hope all is well.

**Comment by lax1dude** [comment]
@xlcee Your title screen has been added to the game here:

[https://github.com/lax1dude/eaglercraft/blob/main/lwjgl-rundir/resources/title/eag.png](https://github.com/lax1dude/eaglercraft/blob/main/lwjgl-rundir/resources/title/eag.png)

Thanks, I'm closing this PR now. Enjoy the new Singleplayer and LAN, it's been open sourced

**Pull request closed without merging**
